EXTRA_INCLUDEPATH += C:\\utils\\my_sql\\my_sql\\include C:\\utils\\postgresql\\pgsql\\include C:\\openssl\\include
EXTRA_LIBDIR += C:\\utils\\my_sql\\my_sql\\lib C:\\utils\\postgresql\\pgsql\\lib
QT_CPU_FEATURES.i386 = 
QT.global_private.enabled_features = alloca_malloc_h alloca sse2 dbus gui network qml-debug sql system-zlib testlib widgets xml
QT.global_private.disabled_features = alloca_h android-style-assets private_tests dbus-linked libudev posix_fallocate reduce_exports reduce_relocations release_tools stack-protector-strong
QT_COORD_TYPE = double
QMAKE_LIBS_ZLIB = -lz
CONFIG += sse2 sse3 ssse3 sse4_1 sse4_2 avx avx2 avx512f avx512bw avx512cd avx512dq avx512er avx512ifma avx512pf avx512vbmi avx512vl compile_examples f16c largefile optimize_debug precompile_header
QT_BUILD_PARTS += libs tools
QT_HOST_CFLAGS_DBUS += 
